# Generated by Django 3.2.12 on 2022-03-26 01:33

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220326_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 4, 33, 9, 997522), editable=False),
        ),
    ]
