# Generated by Django 3.2.12 on 2022-03-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220326_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonetoken',
            options={'verbose_name': 'Phone Token', 'verbose_name_plural': 'Phone Tokens'},
        ),
        migrations.AddField(
            model_name='phonetoken',
            name='invite_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.invitekey'),
        ),
        migrations.AlterField(
            model_name='invitekey',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='invite', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
