# Generated by Django 3.2.12 on 2022-03-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220326_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetoken',
            name='invite_key',
        ),
        migrations.AddField(
            model_name='account',
            name='invite_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.invitekey'),
        ),
    ]
