# Generated by Django 3.2.12 on 2022-03-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220326_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitekey',
            name='slave',
        ),
    ]
