# Generated by Django 3.2.12 on 2022-03-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_invitekey_slave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='invite_key',
            new_name='invite',
        ),
        migrations.AlterField(
            model_name='invitekey',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_invite', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
